apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-hello-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-hello-k8s
  template:
    metadata:
      labels:
        app: sb-hello-k8s
    spec:
      containers:
        - image: ykko21/hello
          imagePullPolicy: Always
          name: sb-hello-k8s
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: sb-hello-k8s
spec:
  selector:
    app: sb-hello-k8s
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  type: NodePort